name: icons_launcher
description: A command-line tool that simplifies the task of updating your Flutter app's launcher icon.
maintainer: Mrr Hak
homepage: https://mrrhak.com
repository: https://github.com/mrrhak/icons_launcher/tree/master
issue_tracker: https://github.com/mrrhak/icons_launcher/issues
version: 3.0.1
funding:
  - https://ko-fi.com/mrrhak
screenshots:
  - description: "Icons Launcher"
    path: assets/icons_launcher_profile.png

dependencies:
  args: ^2.6.0
  image: ^4.5.3
  path: ">=1.8.2 <2.0.0"
  universal_io: ^2.2.2
  yaml: ^3.1.3

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.15
  build_version: ^2.1.1
  lints: ^5.1.1
  test: ^1.25.15

topics:
  - icons
  - app-icon
  - icons-launcher