name: icons_launcher
description: A command-line tool that simplifies the task of updating your Flutter app's launcher icon.
maintainer: Mrr Hak
homepage: https://mrrhak.com
repository: https://github.com/mrrhak/icons_launcher
version: 2.0.0

dependencies:
  args: ^2.3.1
  image: ^3.1.3
  path: ^1.8.1
  universal_io: ^2.0.4
  yaml: ^3.1.1

environment:
  sdk: ">=2.17.1 <3.0.0"

dev_dependencies:
  test: ^1.21.1
  build_runner: ^2.1.11
  build_version: ^2.1.1
