name: Close inactive issues

on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: '5 * * * *'

permissions:
  issues: write

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'mrrhak/icons_launcher' }}
    steps:
      - uses: godofredoc/no-response@0ce2dc0e63e1c7d2b87752ceed091f6d32c9df09
        with:
          token: ${{ github.token }}
          closeComment: >
            Without additional information, we are unfortunately not sure how to
            resolve this issue. We're therefore reluctantly going to close it.

            Feel free to open a new issue with all the required information
            provided, including a [minimal, reproducible sample]. Make sure to
            diligently fill out the issue template.

            Thanks for your contribution.

            [minimal, reproducible sample]: https://stackoverflow.com/help/minimal-reproducible-example
          # Number of days of inactivity before an issue is closed.
          daysUntilClose: 14
          # Only issues with this label will be closed (if they are inactive).
          responseRequiredLabel: waiting for response
